name: Build React App

on:
  push:
    branches: [ "lab8", "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'weather-app/package-lock.json'

      - name: Install dependencies
        working-directory: weather-app
        run: npm ci

      - name: Build project
        working-directory: weather-app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-app-build
          path: weather-app/dist