name: Build React App

on:
  push:
    branches: [ "lab8", "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'weather-app/package-lock.json'
          
      - name: Install dependencies
        working-directory: weather-app
        run: npm ci
          
      - name: Build
        working-directory: weather-app
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: weather-app-build
          path: weather-app/dist